import cv2
import numpy as np
import os
import time
from ultralytics import YOLO
from queue_analytics import QueueAnalytics
from queue_database import create_tables, log_queue_event, log_snapshot



# Edit SOURCE, MODEL, and ZONES before running on a new video.

SOURCE  = r"videos\supermarket.mp4"
OUTPUT  = r"output\queue_monitoring.mp4"
MODEL   = r"models\yolov8n.pt"
TRACKER = "bytetrack.yaml"
CLASSES = [0]  # COCO class 0 = person
SESSION = os.path.basename(SOURCE)

# Zone polygons generated by running select_zones.py.
# Replace with output from select_zones.py when switching to a new scene.
ZONES = {
    "zone1": [(687, 112), (831, 114), (922, 558), (725, 542), (687, 114)],
    "zone2": [(399, 141), (497, 142), (435, 546), (228, 543), (398, 142)],
    "zone3": [(973, 104), (1081, 98), (1253, 408), (1201, 474), (973, 104)],
}

ZONE_COLOURS = [
    (0,   255, 0),
    (0,   165, 255),
    (255, 0,   0),
    (0,   0,   255),
    (255, 0,   255),
    (0,   255, 255),
]

COL_OUTSIDE = (200, 200, 200)
COL_TEXT    = (255, 255, 255)
COL_HUD_BG  = (0, 0, 0)


def get_zone_colour(zone_index):
    return ZONE_COLOURS[zone_index % len(ZONE_COLOURS)]


def draw_zones(frame):
    """Renders zone polygons with semi-transparent fill and name labels."""
    for i, (zone_name, pts) in enumerate(ZONES.items()):
        colour = get_zone_colour(i)
        arr    = np.array(pts, np.int32)

        overlay = frame.copy()
        cv2.fillPoly(overlay, [arr], colour)
        cv2.addWeighted(overlay, 0.1, frame, 0.9, 0, frame)
        cv2.polylines(frame, [arr], isClosed=True, color=colour, thickness=2)

        cx = int(sum(p[0] for p in pts) / len(pts))
        cy = int(sum(p[1] for p in pts) / len(pts))
        cv2.putText(frame, zone_name, (cx - 40, cy),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, colour, 2)


def draw_box(frame, x1, y1, x2, y2, tid, wait_s, zone_name, zone_index):
    """Renders a bounding box for one tracked person.

    Colour reflects zone membership — grey if outside all zones.
    """
    if zone_name:
        color = get_zone_colour(zone_index)
        label = f"ID {tid}  {wait_s:.1f}s  [{zone_name}]"
    else:
        color = COL_OUTSIDE
        label = f"ID {tid}"

    cv2.rectangle(frame, (x1, y1), (x2, y2), color, 2)
    cv2.putText(frame, label, (x1, y1 - 6),
                cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)


def draw_hud(frame, analytics_dict):
    """Renders one metrics panel per zone, stacked vertically on the left."""
    pad     = 8
    lh      = 20
    panel_w = 300

    for i, (zone_name, analytics) in enumerate(analytics_dict.items()):
        colour = get_zone_colour(i)
        lines  = [
            f"{zone_name}",
            f"  Queue    : {analytics.queue_length()}",
            f"  Avg wait : {analytics.average_wait():.1f}s",
            f"  Longest  : {analytics.longest_current_wait():.1f}s",
            f"  Served   : {analytics.total_served()}",
        ]

        top   = i * (pad * 2 + lh * len(lines) + 10)
        h_box = pad * 2 + lh * len(lines)

        overlay = frame.copy()
        cv2.rectangle(overlay, (0, top), (panel_w, top + h_box), COL_HUD_BG, -1)
        cv2.addWeighted(overlay, 0.6, frame, 0.4, 0, frame)
        cv2.rectangle(frame, (0, top), (4, top + h_box), colour, -1)

        for j, line in enumerate(lines):
            cv2.putText(frame, line, (pad + 4, top + pad + lh * (j + 1)),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.5, COL_TEXT, 1)



create_tables()

model = YOLO(MODEL)
cap   = cv2.VideoCapture(SOURCE)
assert cap.isOpened(), f"Cannot open video: {SOURCE}"

w   = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
h   = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = cap.get(cv2.CAP_PROP_FPS) or 30.0

writer = cv2.VideoWriter(OUTPUT, cv2.VideoWriter_fourcc(*"mp4v"), fps, (w, h))

# Per-zone state — one instance of each per zone
analytics_dict = {zone: QueueAnalytics()        for zone in ZONES}
region_polys   = {zone: np.array(pts, np.int32) for zone, pts in ZONES.items()}
prev_ids       = {zone: set()                   for zone in ZONES}

last_snapshot = time.time()

print(f"Tracking {len(ZONES)} zone(s): {list(ZONES.keys())}")
print("Press Q to quit.\n")


for result in model.track(
    source=SOURCE,
    stream=True,
    persist=True,
    tracker=TRACKER,
    classes=CLASSES,
    verbose=False,
):
    frame       = result.orig_img.copy()
    ids_in_zone = {zone: [] for zone in ZONES}

    if result.boxes.id is not None:
        boxes = result.boxes.xyxy.cpu().numpy().astype(int)
        ids   = result.boxes.id.cpu().numpy().astype(int)

        for (x1, y1, x2, y2), tid in zip(boxes, ids):
            cx = float((x1 + x2) / 2)
            cy = float((y1 + y2) / 2)

            person_zone     = None
            person_zone_idx = 0

            # Assign person to the first zone their center falls inside
            for zone_idx, (zone_name, poly) in enumerate(region_polys.items()):
                if cv2.pointPolygonTest(poly, (cx, cy), False) >= 0:
                    ids_in_zone[zone_name].append(tid)
                    person_zone     = zone_name
                    person_zone_idx = zone_idx
                    break

            wait_s = analytics_dict[person_zone].current_waits.get(tid, 0.0) if person_zone else 0.0
            draw_box(frame, x1, y1, x2, y2, tid, wait_s, person_zone, person_zone_idx)

    # Per-zone enter/exit detection and database logging
    for zone_name, analytics in analytics_dict.items():
        current_ids = set(ids_in_zone[zone_name])
        entered     = current_ids - prev_ids[zone_name]
        exited      = prev_ids[zone_name] - current_ids

        for tid in entered:
            log_queue_event(track_id=tid, event_type="enter",
                            zone=zone_name, session=SESSION)

        for tid in exited:
            wait = analytics.current_waits.get(tid, 0.0)
            log_queue_event(track_id=tid, event_type="exit",
                            wait_time=round(wait, 2), zone=zone_name, session=SESSION)

        prev_ids[zone_name] = current_ids
        analytics.update(ids_in_zone[zone_name])

    # Snapshot every 30 seconds one row per zone
    now = time.time()
    if now - last_snapshot >= 30:
        for zone_name, analytics in analytics_dict.items():
            log_snapshot(
                queue_length=analytics.queue_length(),
                average_wait_time=analytics.average_wait(),
                longest_wait_time=analytics.longest_current_wait(),
                total_served=analytics.total_served(),
                zone=zone_name,
                session=SESSION
            )
        last_snapshot = now

    draw_zones(frame)
    draw_hud(frame, analytics_dict)

    for zone_name, analytics in analytics_dict.items():
        print(
            f"[{zone_name}] "
            f"Queue: {analytics.queue_length():3d} | "
            f"Avg wait: {analytics.average_wait():5.1f}s | "
            f"Longest: {analytics.longest_current_wait():5.1f}s | "
            f"Served: {analytics.total_served()}"
        )

    writer.write(frame)
    cv2.imshow("Queue Monitor", frame)

    if cv2.waitKey(1) & 0xFF == ord("q"):
        break


cap.release()
writer.release()
cv2.destroyAllWindows()
print(f"\nDone. Video saved to: {OUTPUT}")
